name: Two-Job Workflow
on:
  pull_request:
    paths:
      - 'prod/dns/jarvis-dns/**'

jobs:
  first-job:
    if: github.event.pull_request.commits == 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate commit author and jarvis-dns folder
        run: |
          # Validate the commit author
          COMMIT_AUTHOR=$(git log --format='%an' -n 1)
          if [ "$COMMIT_AUTHOR" != "rahulrajm" ]; then
            echo "Commit author is not rahulrajm. Exiting."
            exit 1
          fi

      - name: Run first job
        run: echo "Running first job"

  second-job:
    runs-on: ubuntu-latest

    needs: first-job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run second job
        run: echo "Running second job"
